CherrygroveCity_MapScripts::
	.byte 0
CherrygroveCity_EventScript_Flowers::
	msgbox CherrygroveCity_Text_Flowers, MSGBOX_NPC
	end
CherrygroveCity_Text_Flowers::
	.string "These are placeholder flowers.\p"
	.string "Do you wonder what that means?\n"
	.string "I'll tell you.\p"
	.string "One day, these flowers will look different.\n"
	.string "When will that happen?\p"
	.string "That, I couldn't tell you.$"
